- name: Configure EC2 Instance
  hosts: all
  become: yes
  tasks:
    - name: Set Timezone to KST
      command: timedatectl set-timezone Asia/Seoul

    - name: Install JDK 17
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Enable and Start Nginx
      systemd:
        name: nginx
        enabled: yes
        state: started
