name: CI/CD for Spring Boot
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build -x test

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ls -l ~/.ssh

      - name: Deploy to AWS EC2
        run: |
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no build/libs/*.jar ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu/app.jar
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            sudo pkill -f 'java -jar'
            nohup java -jar /home/ubuntu/app.jar > /dev/null 2>&1 &
          EOF
