name: CI/CD for Spring Boot
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set Timezone to KST
        run: |
          sudo ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
          echo "Timezone set to: $(date)"

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build -x test

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' > ~/.ssh/github-action-key
          chmod 600 ~/.ssh/github-action-key
          ls -l ~/.ssh

      - name: Deploy to AWS EC2
        run: |
          ssh -i ~/.ssh/github-action-key -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }}
          scp -T -i ~/.ssh/github-action-key -o StrictHostKeyChecking=no build/libs/springboot-hello-0.0.1-SNAPSHOT.jar ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu/app.jar
          ssh -i ~/.ssh/github-action-key -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            sudo pkill -f 'java -jar'
            nohup java -jar /home/ubuntu/app.jar > /dev/null 2>&1 &
          EOF
